#ifndef INCLUDED_SOVEREIGN_DATA_STRUCTURES_LEVEL_CHUNK_CELL_HPP_
#define INCLUDED_SOVEREIGN_DATA_STRUCTURES_LEVEL_CHUNK_CELL_HPP_

namespace sov {

	struct LevelChunkCell {
		bool empty{ false };
	};

}

#endif // INCLUDED_SOVEREIGN_DATA_STRUCTURES_LEVEL_CHUNK_CELL_HPP_