#ifndef INCLUDED_SOVEREIGN_SERVICES_INTERFACES_I_LEVEL_DATA_MUTATION_SERVICE_HPP_
#define INCLUDED_SOVEREIGN_SERVICES_INTERFACES_I_LEVEL_DATA_MUTATION_SERVICE_HPP_

namespace sov {
	
	class ILevelDataMutationService {
	protected:
		virtual ~ILevelDataMutationService(void) = 0 {}

	public:

	};

}

#endif // INCLUDED_SOVEREIGN_SERVICES_INTERFACES_I_LEVEL_DATA_MUTATION_SERVICE_HPP_